# Basic Information
title: Yuanhang(Leo) Yu
position: PhD Student
affiliation: London School of Economics
affiliation_link: https://www.lse.ac.uk/economics
affiliation_logo: ./assets/img/logo.svg
email: y.yu42@lse.ac.uk
emailalt: y.yu42@lse.ac.uk

# Search Engine Optimization (SEO)
keywords: Yuanhang(Leo) Yu, Yuanhang Yu, Yuanhang, Leo Yu, Yuanhang, economics, econ
canonical: https://yuanhang-leo-yu.github.io/
description: Yuanhang(Leo) Yu is a PhD student at the London School of Economics. His research insterest includes spatial economics, international trade, and environmental economics.

# The option is used to enable the MPI Informatics template.
enable_mpi_logo: false

# Links
# google_scholar: https://scholar.google.com/citations?user=Uf9GqRsAAAAJ
cv_link: https://yuanhang-leo-yu.github.io/files/pdf/CV.pdf
github_link: https://github.com/yuanhang-leo-yu/
linkedin: 
twitter: https://x.com/yyhleo289

# Images
avatar: ./files/img/profile_1.jpg
favicon: ./assets/img/favicon.ico
favicon_dark: ./assets/img/favicon.ico

# Analytics
# Please remove the following lines about analytics services if you fork my project.
# Otherwise, the analytics information of your website will be recorded to my Google Analytics and ClustrMaps accounts.
#google_analytics: G-3B09YM4Y7W
#google_tag: G-3B09YM4Y7W
#clustrmaps_link: //clustrmaps.com/globe.js?d=QsP-3Qm0fSNU94UxmGJF47QKd4gsH-E2IA0XQyxXREM

# General Data Protection Regulation (GDPR) information
# If you don't need to add the GDPR information, you may remove the following lines.
# imprint: https://imprint.mpi-klsb.mpg.de/inf/people.mpi-inf.mpg.de/yaliu
# data_protection: https://data-protection.mpi-klsb.mpg.de/inf/people.mpi-inf.mpg.de/yaliu?lang=en

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - minimal-light.gemspec
  - CNAME
